apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-app
  template:
    metadata:
      labels:
        app: message-app
    spec:
      containers:
      - image:  akash125/message-app:v1
        imagePullPolicy: Always
        name: message-app
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: message-configmap
  